swagger: '2.0'
info:
  version: 1.0.0
  title: API
  description: API
host: localhost:3000
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

# TODO: Split paths into multiple files once this issue has been resolved https://github.com/apigee-127/sway/issues/92
paths:
  /login:
    x-swagger-router-controller: SessionsController
    post:
      operationId: login
      description: Login with user credentials
      parameters:
        - $ref: "#/parameters/DataTypeSession"
        - name: credentials
          in: body
          description: User credentials
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
      responses:
        200:
          description: Login response
          schema:
            $ref: '#/definitions/LoginResponse'

securityDefinitions:
  User:
    type: apiKey
    name: Authorization
    in: header

definitions:
  $ref: ./definitions/index.yaml

parameters:
  $ref: ./parameters/index.yaml
